#!/bin/bash
 
nAddr=0
fSize=4095
cByte=""
iStart=0
rm -rf ../boot_code.vhd

#vhdl descriptor
echo "--This file is automatically generated, please do not change the content" >> ../boot_code.vhd
echo "--file content description:" >> ../boot_code.vhd
echo "--boot code for flash" >> ../boot_code.vhd

#vhdl header
echo "LIBRARY IEEE;" >> ../boot_code.vhd
echo "USE IEEE.STD_LOGIC_1164.ALL;" >> ../boot_code.vhd
echo "PACKAGE CONSTANTS IS" >> ../boot_code.vhd

#vhdl package start 
echo "TYPE c_mem IS ARRAY (0 TO 2**12 -1) OF STD_LOGIC_VECTOR(7 DOWNTO 0);" >> ../boot_code.vhd
echo "CONSTANT boot_code : c_mem:=(" >> ../boot_code.vhd
while read line
do
	cByte=$(echo $line | cut -d'_' -f2)
	#little endian format
	echo x\"${cByte:6:2}\", >> ../boot_code.vhd
	echo x\"${cByte:4:2}\", >> ../boot_code.vhd
	echo x\"${cByte:2:2}\", >> ../boot_code.vhd
	echo x\"${cByte:0:2}\", >> ../boot_code.vhd
	#32 bit word equals to 4 addresses in flash memory
	nAddr=$(($nAddr + 4))	
done < ./spi_stim.txt

while [ $nAddr != $fSize ]
do
	echo x\"00\", >>../boot_code.vhd
	nAddr=$(($nAddr + 1))
done	

echo x\"00\"\)\; >>../boot_code.vhd

#vhdl package end
echo "END PACKAGE CONSTANTS;" >> ../boot_code.vhd
