#!/bin/bash

# **************************************************************************************
#	Filename:	programmer.sh
#	Project:	CNL_RISC-V
#  	Version:	1.0
#	History:
#	Date:		9 Sep 2022
#
# Copyright (C) 2022 CINI Cybersecurity National Laboratory
#
# This source file may be used and distributed without
# restriction provided that this copyright statement is not
# removed from the file and that any derivative work contains
# the original copyright notice and the associated disclaimer.
#
# This source file is free software; you can redistribute it
# and/or modify it under the terms of the GNU Lesser General
# Public License as published by the Free Software Foundation;
# either version 3.0 of the License, or (at your option) any
# later version.
#
# This source is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General
# Public License along with this source; if not, download it
# from https://www.gnu.org/licenses/lgpl-3.0.txt
#
# **************************************************************************************
#
#	File content description:
#	#script for programming fpga using Quartus II programmer
#
# **************************************************************************************

PROGRAMMER=$(which quartus_pgm)

JTAG_CFG=$(which jtagconfig)

DEVICE=$(sudo $JTAG_CFG | grep DE-SoC | cut -d' ' -f3)

if [ -z "$DEVICE" ]
then
    exit 1
fi

DEVICE="DE-SoC$DEVICE"

#quartus_pgm needs to be run as super user otherwise is not able to see the usb blaster
#cdf file (Chain Description File) if not present can be generated by quartus programmer gui
sudo $PROGRAMMER --cable=$DEVICE output_files/mc2101.cdf
